server:
  port: 8081

spring:
  application:
    name: book-service
  datasource:
    url: jdbc:mysql://localhost:3306/book_store
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rinshad3657
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
