server:
  port: 8083

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rinshad3657
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/